export default {
    name: '',
    value: null,
    fields: null,
    type: 'v-base',
    extraBind: {},
    title: '',
    headerHelp: '',
    orderFields: {},
    paginator: true,
    rows: 20,
    loaded: false,
    route: null,
    routeName: null,
    defaultWidgetType: 'w-text',
    fieldsConfig: {},
    actionsConfig: {},
    metadata: {},
    pagination: {},
    selectionMode: null,
    autoload: true,
    blocked: false,
    modelName: null,
}
