export default {
    name: '',
    value: null,
    fields: null,
    type: 'v-base',
    extraBind: {},
    title: '',
    headerHelp: '',
    loaded: false,
    route: null,
    routeName: null,
    defaultWidgetType: 'w-input',
    fieldsConfig: {},
    actionsConfig: {},
    metadata: {},
    autoload: true,
    actionDivider: false,
    blocked: false,
    modelName: null,
}
