export default {
    name: '',
    value: null,
    fields: null,
    type: 'v-base',
    extraBind: {},
    title: '',
    headerHelp: '',
    orderFields: {},
    paginator: true,
    paginatorPosition: 'both',
    rows: 20,
    loaded: false,
    route: null,
    routeName: null,
    defaultWidgetType: 'w-text',
    fieldsConfig: {},
    actionsConfig: {},
    metadata: {},
    pagination: {},
    selectionMode: 'multiple',
    autoload: true,
    recordActionsPosition: 'end',
    actionsLayout: 'simple',
    actionsLayoutTitle: '',
    actionRecordLayout: 'simple',
    actionRecordLayoutTitle: '',
    blocked: false,
    modelName: null,
    hiddenColumns: [],
    //numeroRecordsLabel : null, // label del numero dei records
}
